// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0x72R5w-kN4mx013VeIn55ePL-C0F1xw',
    appId: '1:123566159580:ios:52117c77e417deb6e5e619',
    messagingSenderId: '123566159580',
    projectId: 'brew-crew-2e2f3',
    storageBucket: 'brew-crew-2e2f3.appspot.com',
    iosClientId: '123566159580-1844i8829ilrujlpbb1ms10re8e0f4lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0x72R5w-kN4mx013VeIn55ePL-C0F1xw',
    appId: '1:123566159580:ios:52117c77e417deb6e5e619',
    messagingSenderId: '123566159580',
    projectId: 'brew-crew-2e2f3',
    storageBucket: 'brew-crew-2e2f3.appspot.com',
    iosClientId: '123566159580-1844i8829ilrujlpbb1ms10re8e0f4lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
